#!/bin/sh
# This is a sample DAEMON file which is started at boottime. iIt must be names
# "start" here and will be renamed according to your Pluginname during
# installation. CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boottime!
# Will be executed as user "root".
#
# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation
#
if [ -d /run/shm/alex2lox/ ] ; then 
bash  REPLACELBPHTMLAUTHDIR/start.sh -a
cp $PDATA/.alexa.devicelist.json  $PDATA/tmp/.alexa.devicelist.json
cp $PDATA/.alexa.cookie  $PDATA/.alexa.cookie
echo Ram Disk vorhanden
chown -cR loxberry /run/shm/alex2lox
else
bash  REPLACELBPHTMLAUTHDIR/start.sh -a
cp $PDATA/.alexa.devicelist.json  $PDATA/tmp/.alexa.devicelist.json
cp $PDATA/.alexa.cookie  $PDATA/.alexa.cookie
mkdir /run/shm/alex2lox
chmod a+w /run/shm/alex2lox > /dev/null 2>&1
#chown -cR loxberry /run/shm/alex2lox
chmod -R 0777 REPLACELBPDATADIR


fi
bash  REPLACELBPHTMLAUTHDIR/start.sh -a
cp $PDATA/.alexa.devicelist.json  /tmp/.alexa.devicelist.json
cp $PDATA/.alexa.cookie  /tmp/.alexa.cookie
cp -a REPLACELBPDATADIR/. /tmp/
exit 0
